services:
  labbit:
    image: n48ll/labbit:latest
    ports:
      - 3000:3000
    volumes:
      - ./data/boards:/app/data/boards
      - ./data/icons:/app/data/icons
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
